[package]
name = "mpr"
version = "0.1.0"
description = "The official command-line interface for the makedeb Package Repository"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.19"
clap = { version = "3.1.18", features = ["cargo", "env"] }
dirs = "4.0.0"
exitcode = "1.1.2"
flate2 = "1.0.24"
quit = "1.1.4"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
